services:
  fluentbit:
    image: fluent/fluent-bit:1.9
    container_name: fluentbit
    user: "0"
    volumes:
      - /docker/apache/log:/apache/log:ro
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./apache_to_gelf.lua:/fluent-bit/etc/apache_to_gelf.lua
      # Optionally, if you create a parsers.conf:
      # Fluent Bit will create its database file here
      - fluentbit_db:/fluent-bit
    networks:
      - graylog_graynet
    restart: unless-stopped

volumes:
  fluentbit_db:

networks:
  graylog_graynet:
    external: true

